### ISSUE TITLE
How to increase debug level?

### ISSUE THREAD

**Issue by tonypottera24** [Stranger6667/css-inline#124]
I'm using python version css-inline to process the HTML rendered by Django `render_to_string` function.
The HTML includes bootstrap and some other common css libraries.

```
html_message = render_to_string('xxx.html')
html_message = css_inline.inline(html_message)
```

It gives the following error messages.
```
[2021-09-05 16:03:25,025: ERROR/ForkPoolWorker-14] Task config.tasks.send_mail_celery[c09d9b28-8384-4854-b1ae-65a0997c8606] raised unexpected: InlineError('No such file or directory (os error 2)')
Traceback (most recent call last):
  File ".../venv/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File ".../venv/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File ".../config/tasks.py", line 29, in send_mail_celery
    html_message = css_inline.inline(html_message)
css_inline.InlineError: No such file or directory (os error 2)
```
Does anyone know how to identify which file is not found?

**Comment by Stranger6667** [comment]
Hi @tonypottera24 !

Thanks for reporting :) It is definitely something to improve - I'll work on extending the `InlineError` type to include more info

**Comment by tonypottera24** [comment]
@Stranger6667 thank you for your help.
I think I've identified the problem.

After I remove all local links, the error is gone.
```
<link rel="stylesheet" href="/static/vendor/css/bootstrap-multiselect.css" type="text/css" />
```
