### ISSUE TITLE
Open Handle

### ISSUE THREAD

**Issue by BijanRegmi** [Stranger6667/css-inline#370]
While running tests with jest, it detects open handle.

```
└──> $ npm run test

> css-inline@1.0.0 test
> jest --detectOpenHandles --config ./jest.config.js

 PASS  ./test.spec.js (10.133 s)
  css-inline
    ✓ nop (6 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        10.173 s, estimated 11 s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  CustomGC

    > 1 | const { inline } = require("@css-inline/css-inline");
        |                    ^
      2 |
      3 | describe("css-inline", () => {
      4 |     jest.setTimeout(30000);

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:1018:29)
      at Object.<anonymous> (node_modules/@css-inline/css-inline/index.js:190:31)
      at Object.require (test.spec.js:1:20)
```

I have linked minimal reproduction repo [here](https://github.com/BijanRegmi/css-inline-minRE)

**Comment by AlexDieRobbe** [comment]
I can also reproduce it while using `@css-inline/css-inline` in [NestJS](https://nestjs.com/).

While running the tests with Jest, I get the following error:

```md
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
1 | import { Module } from '@nestjs/common';
    > 2 | import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
        | ^

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:1018:29)
      **at Object.<anonymous> (node_modules/@css-inline/css-inline/index.js:141:29)**
      at Object.<anonymous> (node_modules/@nestjs-modules/mailer/dist/adapters/handlebars.adapter.js:7:22)
      at Object.<anonymous> (src/app.module.ts:2:1)
      at Object.<anonymous> (src/main.ts:14:1)
      at Object.<anonymous> (src/tests/headers.e2e-spec.ts:2:1)
```
